
from classes.lesson import Lesson

Lesson(1).print_definition()
Lesson(2).print_definition()
Lesson(3).print_definition()
Lesson(4).print_definition()
Lesson(5).print_definition()
Lesson(6).print_definition()
Lesson(7).print_definition()
Lesson(8).print_definition()
Lesson(9).print_definition()
Lesson(10).print_definition()
Lesson(11).print_definition()
Lesson(11, True).print_definition()
Lesson(12).print_definition()
Lesson(12, True).print_definition()
Lesson(13).print_definition()
Lesson(14).print_definition()
Lesson(15).print_definition()
Lesson(16).print_definition()
Lesson(17).print_definition()
Lesson(18).print_definition()
Lesson(19).print_definition()
Lesson(20).print_definition()
Lesson(20, True).print_definition()
Lesson(21).print_definition()
Lesson(22).print_definition()
Lesson(22, True).print_definition()
Lesson(23).print_definition()
Lesson(23, True).print_definition()

# lesson.print_all()
# lesson.print_pinyin()
# lesson.print_chinese()
# lesson.print_definition()
