
from classes.lesson import Lesson

lesson = Lesson(1).print_definition()
lesson = Lesson(2).print_definition()
lesson = Lesson(3).print_definition()
lesson = Lesson(4).print_definition()
lesson = Lesson(5).print_definition()
lesson = Lesson(6).print_definition()
lesson = Lesson(7).print_definition()
lesson = Lesson(8).print_definition()
lesson = Lesson(9).print_definition()
lesson = Lesson(10).print_definition()
lesson = Lesson(11).print_definition()
lesson = Lesson(11, True).print_definition()
lesson = Lesson(12).print_definition()
lesson = Lesson(12, True).print_definition()
lesson = Lesson(13).print_definition()
# lesson.print_all()
# lesson.print_pinyin()
# lesson.print_chinese()
# lesson.print_definition()
