#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON14 = [
    ["ZHŌNGwǓ",      "", "mediodía", "NOM"],
    ["GĀNGCÁI",      "", "recién", "NOM"],
    ["YÓUJÚ",        "", "oficina de correos", "NOM"],
    ["YÓU",          "", "enviar por correo", "VER"],
    ["JÚ",           "", "oficina", "NOM"],
    ["JÌ",           "", "enviar, mandar (algo físico)", "VER"],
    ["DǍSǍO",        "", "limpiar", "VER"],
    ["DǍ",           "", "golpear", "VER"],
    ["SǍO",          "", "barrer", "NOM"],
    ["ZĀNG",         "", "sucio", "ADJ"],
    ["GĀNJÌNG",      "", "limpio", "ADJ"],
    ["BÙHǍOYÌSI",    "", "sentirse avergonzado", "FH"],
    ["XǏ",           "", "lavar", "VER"],
    ["WÀIPÓ",        "", "abuela (materna)", "NOM"],
    ["LǍOLǍO",       "", "abuela (materna)", "NOM"],
    ["ZHŌNGXUÉ",     "", "liceo, secundario", "NOM"],
    ["DǍGŌNG",       "", "trabajar a tiempo parcial", "VER"],
    ["NÁNFĀNG",      "", "parte sur", "NOM"],
    ["LǙXÍNG",       "", "viajar", "VER"],
    ["XIǍNG",        "", "echar de menos", "VER"],
    ["LIÚXUÉSHĒNG",  "", "estudiante extranjero", "NOM"],
    ["ZHÙ",          "", "vivir, residir", "VER"],
    ["LÓU",          "", "edificio / piso", "NOM"],
    ["DUÌ",          "", "correcto", "ADJ"],
    ["CUÒ",          "", "incorrecto", "ADJ"],
    ["NIÀN",         "", "leer (en voz alta)", "VER"],
    ["SHĒNGCÍ",      "", "nueva palabra", "NOM"],
    ["SHĒNG",        "", "nuevo", "ADJ"],
    ["CÍ",           "", "palabra", "NOM"],
    ["FÙXÍ",         "", "repasar", "VER"],
    ["KÈWÉN",        "", "texto, lección de texto", "NOM"],
    ["LIÀNXÍ",       "", [["practicar", "VER"], ["ejercicio (en un libro)", "NOM"]]],
    ["LIÀN",         "", "practicar", "VER"],
    ["KǑUYǓ",        "", "oral / lengua hablada", "NOM"],
    ["YǓFǍ",         "", "gramática", "NOM"],
    ["GUÒ",          "", "celebrar (un cumpleaños, vacaciones)", "VER"],
    ["JIÉ",          "", "festividad", "NOM"],
    ["LǏWÙ",         "", "regalo", "NOM"],
    ["SHÈNGDÀN",     "", "Navidad", "NP"],
    ["ŌUZHŌU",       "", "Europa", "NP"],
    ["LĀMĚI",        "", "América Latina", "NP"],
    ["SHÀNGHǍI",     "", "Shanghai", "NP"]
]
