#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON13 = [
    ["GŪNIANG",      "", "chica, niña", "NOM"],
    ["TĪNGSHUŌ",     "", "oír decir", "VER"],
    ["TĪNG",         "", "escuchar", "VER"],
    ["DÉ",           "", "tener, conseguir, agarrar", "VER"],
    ["GÀOSU",        "", "decir, contar", "VER"],
    ["JIÀN",         "", "clasificador para pieza de ropa, parte", "CLA"],
    ["SHÌR",         "", "asunto, cosa, negocio", "NOM"],
    ["SÀNBÙ",        "", "dar un paseo, caminar", "VMO"],
    ["BÙ",           "", "paso", "NOM"],
    ["DIÀN",         "", "electricidad", "NOM"],
    ["DIÀNYǏNG",     "", "película", "NOM"],
    ["DIÀNYǏNGYUÀN", "", "cine", "NOM"],
    ["YǏNGZI",       "", "sombra", "NOM"],
    ["KĚSHÌ",        "", "pero", "CON"],
    ["ZHǍO",         "", "buscar", "VER"],
    ["FÁNGZI",       "", "casa", "NOM"],
    ["ZŪ",           "", "alquilar", "VER"],
    ["JIĀN",         "", "clasificador para habitación, casa, etc.", "CLA"],
    ["CHÚFÁNG",      "", "cocina", "NOM"],
    ["CÈSUǑ",        "", "baño", "NOM"],
    ["FÁNGZŪ",       "", "(dinero del) alquiler", "NOM"],
    ["GŌNGSĪ",       "", "empresa", "NOM"],
    ["KĀFĒI",        "", "café", "NOM"],
    ["SÙSHÈ",        "", "dormitorio, habitación", "NOM"],

    ["BÀN",          "", "hacer / hacer frente a", "VER"],
    ["DǍDIÀNHUÀ",    "", "llamar por teléfono", "VMO"],
    ["DIÀNHUÀ",      "", "llamada telefónica / teléfono", "NOM"],
    ["RÀNG",         "", "permitir, dejar", "VER"],
    ["BĀNGZHÙ",      "", [["ayudar", "VER"], ["ayuda", "NOM"]]],
    ["WÉI",          "", "hola", "OTR"],
    ["WÈI",          "", "clasificador personas (manera educada)", "CLA"],
    ["JĪNGLǏ",       "", "gerente", "NOM"],
    ["KĚNÉNG",       "", "quizás, puede que", "VAUX"],
    ["CHĪFÀN",       "", "comer, tomar (una comida)", "VMO"],
    ["FÀN",          "", "comida", "NOM"],
    ["DĚNG",         "", "esperar", "VER"],
    ["QǏNG",         "", "invitar, solicitar, pedir", "VER"],
    ["JIĀMĚI",       "", "(nombre de inmobiliaria)", "NP"]
]
