#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON9 = [
    ["JĪNNIÁN",   "", "este año", "NOM"],
    ["NIÁN",      "", "año", "NOM"],
    ["SUÌ",       "", "año (edad)", "CLA"],
    ["KÈ",        "", "clase / lección", "NOM"],
    ["XĪNGQĪ",    "", "semana", "NOM"],
    ["SHÀNGWǓ",   "", "por la mañana", "NOM"],
    ["SHÀNG",     "", "encima / pasado", "NOM"],
    ["XIÀWǓ",     "", "por la tarde", "NOM"],
    ["XIÀ",       "", "debajo / próximo", "NOM"],
    ["XĪNGQĪRÌ",  "", "domingo", "NOM"],
    ["SHĒNGRI",   "", "cumpleaños", "NOM"],
    ["SHĒNG",     "", [["nacer", "VER"], ["vida", "NOM"]]],
    ["DUŌDÀ",     "", "¿cuántos años / qué edad?", "PI"],
    ["CHŪSHĒNG",  "", [["nacer", "VER"], ["nacimiento", "NOM"]]],
    ["CHŪ",       "", [["salir", "VER"], ["fuera", "ADV"]]],
    ["SHǓ",       "", "nacer en el año de", "VER"],
    ["MǍ",        "", "caballo", "NOM"],
    ["JÙHUÌ",     "", "fiesta", "NOM"],
    ["HUÌ",       "", "reunión", "NOM"],
    ["ZHÙHÈ",     "", [["felicitar", "VER"], ["felicitación", "NOM"]]],
    ["ZHÙ",       "", [["desear, felicitar", "VER"], ["deseo", "NOM"]]],
    ["CĀNJIĀ",    "", "participar / asistir / integrarse", "VER"],
    ["GUÒ",       "", [["celebrar", "VER"], ["cruz", "NOM"]]],
    ["CHĪ",       "", "comer", "VER"],
    ["DÀNGĀO",    "", "pastel / torta", "NOM"],
    ["DÀN",       "", "huevo", "NOM"],
    ["GĀO",       "", "pastel", "NOM"],
    ["MǍI",       "", "comprar", "VER"],
    ["PÍNG",      "", "botella", "CLA"],
    ["HÓNG",      "", "rojo", "ADJ"],
    ["PÚTÁOJIǓ",  "", "vino", "NOM"],
    ["PÚTÁO",     "", "uva", "NOM"],
    ["JIǓ",       "", "bebida alcohólica", "NOM"],
    ["BĚIJĪNG",   "", "Pekín", "NP"],
    ["KUÀILÈ",    "", "felíz", "ADJ"],
    ["PIÀOLIANG", "", "guapa (chica) / bonito (cosas)", "ADJ"],
    ["KǍOYĀ",     "", "pato laqueado", "NOM"],
    ["YĀ",        "", "pato", "NOM"],
    ["SHÒUMIÀN",  "", "tallarines de la longevidad", "NOM"],
    ["MIÀN",      "", "tallarín / cara", "NOM"],
    ["YUÈ",       "", "mes / luna", "NOM"],
    ["WǍNSHANG",  "", "noche", "NOM"],
    ["ÉRZI",      "", "hijo", "NOM"]
]
