#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON12 = [
    ["QUÁNSHĒN",   "全身", "todo (el cuerpo)", "NOM"],
    ["QUÁN",       "全", "completo, todo", "ADJ"],
    ["SHĒN",       "身", "cuerpo", "NOM"],
    ["SHŪFU",      "舒服", "cómodo, bien", "ADJ"],
    ["MĚI",        "每", "cada", "PRO"],
    ["DUÀNLIÀN",   "锻炼", "hacer ejercicio físico", "VER"],
    ["TÓU",        "头", "cabeza", "NOM"],
    ["TÉNG",       "疼", "doloroso", "ADJ"],
    ["SǍNGZI",     "嗓子", "garganta", "NOM"],
    ["XIǍNG",      "想", "pensar, querer hacer algo", "VAUX"],
    ["YĪYUÀN",     "医院", "hospital", "NOM"],
    ["KÀNBÌNG",    "看病", "ir al médico", "VMO"],
    ["BÌNG",       "病", [["enfermedad", "NOM"], ["ponerse enfermo", "VER"]]],
    ["SHĒNTǏ",     "身体", "cuerpo, salud", "NOM"],
    ["YÀO",        "要", "deber, querer hacer algo", "VAUX"],
    ["BA",         "吧", "(partícula modal)", "OTR"],
    ["HÁISHI",     "还是", "o", "CON"],
    ["YÌQǏ",       "一起", "juntos", "ADV"],
    ["LĚNG",       "冷", "frío", "ADJ"],
    ["CHUĀN",      "穿", "llevar puesto", "VER"],
    ["YĪFU",       "衣服", "ropa", "NOM"],
    ["XIŪXI",      "休息", [["descansar", "VER"], ["descanso", "NOM"]]],
    ["GĚI",        "给", "a, para", "PRE"],
    ["GUÀHÀO",     "挂号", "registrarse (en un hospital)", "VER"],
    ["YǑUDIǍNR",   "有点儿", "un poco", "ADV"],
    ["FĀYÁN",      "发炎", "inflamarse", "VMO"],
    ["FĀSHĀO",     "发烧", "tener fiebre", "VMO"],
    ["SHĀO",       "烧", "quemar", "VER"],
    ["GǍNMÀO",     "感冒", [["tener resfriado", "VER"], ["resfrío", "NOM"]]],
    ["ZHÙYUÀN",    "住院", "estar en el hospital", "VMO"],
    ["SHUǏ",       "水", "agua", "NOM"],
    ["YÀO",        "药", "medicina", "NOM"],
    ["YUÀNYÌ",     "愿意", "estar dispuesto a hacer algo", "VAUX"],
    ["ZHŌNGYÀO",   "中药", "medicina tradicional china", "NOM"],
    ["XĪYÀO",      "西药", "medicina occidental", "NOM"],
    ["XĪ",         "西", "oeste, occidental", "NOM"]
]
