#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON16 = [
    ["BǍ",             "", "(indicar que la acción tiene efecto sobre el objeto)", "PRE"],
    ["WÀNG",           "", "olvidar", "VER"],
    ["TÚSHŪGUǍN",      "", "biblioteca", "NOM"],
    ["TÚSHŪ",          "", "libros", "NOM"],
    ["GUǍN",           "", "tienda / un lugar para actividades culturales", "NOM"],
    ["BÀNGŌNGSHÌ",     "", "oficina", "NOM"],
    ["BÀNGŌNG",        "", "trabajar (en una oficina)", "VER"],
    ["SHÌ",            "", "habitación", "NOM"],
    ["SHÀNG",          "", "arriba / subir / última / anterior", "OTR"],
    ["XIÀ",            "", "abajo / bajar / próximo", "OTR"],
    ["XIĀN",           "", "primero / antes", "ADV"],
    ["JIÈZHŪZHÈNG",    "", "carné de biblioteca", "NOM"],
    ["JIÈ",            "", "tomar prestado / prestar", "VER"],
    ["ZHÈNG",          "", "certificado / tarjeta", "NOM"],
    ["YÍHUÌR",         "", "un rato", "OTR"],
    ["DÀI",            "", "traer / llevar", "VER"],
    ["TIÁN",           "", "rellenar", "VER"],
    ["BIǍO",           "", "formulario / tabla / lista", "NOM"],
    ["NÁ",             "", "agarrar", "VER"],
    ["MÀN",            "", "lento, lentamente", "ADJ"],
    ["BÙXIÍNG",        "", "no estar permitido algo", "VER"],
    ["SHĒNGHUÓ",       "", [["vivir", "VER"], ["vida", "NOM"]]],
    ["ZÌJǏ",           "", "uno mismo", "PRO"],
    ["XÌNGMÍNG",       "", "nombre", "NOM"],
    ["XÌNGBIÉ",        "", "sexo", "NOM"],
    ["ZHÍYÈ",          "", "profesión", "NOM"],
    ["JIĀO",           "", "entregar / pagar (el alquiler, etc.)", "VER"],

    ["CHÁNG",          "", "largo", "ADJ"],
    ["JIǓ",            "", "largo (tiempo)", "ADJ"],
    ["KǍOSHÌ",         "", [["hacer un examen", "VER"], ["examen", "NOM"]]],
    ["KǍO",            "", [["hacer un examen", "VER"], ["examen", "NOM"]]],
    ["BÚCUÒ",          "", "no estar mal", "ADJ"],
    ["FĀNYÌ",          "", [["traducir / interpretar", "VER"], ["traductor / intérprete", "NOM"]]],
    ["XĪN",            "", "nuevo", "ADJ"],
    ["KÈBĚN",          "", "libro de texto", "NOM"],
    ["CHŪ",            "", [["salir", "VER"], ["fuera", "ADV"]]],
    ["HUÁN",           "", "devolver", "VER"],
    ["GUÒQĪ",          "", "haber vencido (un plazo)", "VMO"],
    ["GUÒ",            "", "aprobar (un examen)", "VER"],
    ["QĪ",             "", "período de tiempo", "NOM"],
    ["FÁKUǍN",         "", [["poner una multa", "VER"], ["multa", "NOM"]]],
    ["FÁ",             "", "sancionar, penalizar", "VER"],
    ["KUǍN",           "", "suma (de dinero)", "NOM"],
    ["DIÀNNǍO",        "", "computadora", "NOM"],
    ["DIÀN",           "", "electricidad", "NOM"],
    ["NǍO",            "", "cerebro", "NOM"],
    ["CHÁ",            "", "comprobar, buscar", "VER"],
    ["SHÍYÒNG",        "", "práctico", "ADJ"]
]
