#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON17 = [
    ["QÍPÁO",     "", "vestido en estilo chino", "NOM"],
    ["BǏ",        "", "que (indica comparación)", "PRE"],
    ["MÀI",       "", "vender", "VER"],
    ["MǍI",       "", "comprar", "VER"],
    ["ZHŌNGSHÌ",  "", "estilo chino", "ADJ"],
    ["SHÌ",       "", "tipo, estilo", "NOM"],
    ["YǏJĪNG",    "", "ya", "ADV"],
    ["SHĀNGDIÀN", "", "tienda", "NOM"],
    ["SHĀNG",     "", "comercio, negocios", "NOM"],
    ["DIÀN",      "", "tienda", "NOM"],
    ["JÍ (LE)",   "", "extremadamente", "ADV"],
    ["YÍDÌNG",    "", "deber, seguramente", "ADV"],
    ["CHÀ",       "", "que no es estándar, pobre, malo", "ADJ"],
    ["KĀISHǏ",    "", "empezar", "VER"],
    ["TÀIJÍQUÁN", "", "taichi", "NOM"],
    ["TÀO",       "", "juego, conjunto", "CLA"],
    ["SHUÀI",     "", "guapo (chico)", "ADJ"],
    ["YÁNSÈ",     "", "color", "NOM"],
    ["HĒI",       "", "negro", "ADJ"],
    ["HÓNG",      "", "rojo", "ADJ"],
    ["BÁI",       "", "blanco", "ADJ"],
    ["PIÁNYI",    "", "barato", "ADJ"],
    ["GŌNGYUÁN",  "", "parque", "NOM"],
    ["ZǑU",       "", "caminar, ir, andar", "VER"],

    ["XIǍOSHÍ",     "", "hora", "NOM"],
    ["GUÒQÙ",       "", "pasar", "VER"],
    ["CHÈNSHĀN",    "", "camisa", "NOM"],
    ["LǛ",          "", "verde", "ADJ"],
    ["YÀNGZI",      "", "forma, ejemplo, modelo, patrón", "NOM"],
    ["SHÒUHUÒYUÁN", "", "dependiente, vendedor", "NOM"],
    ["SHÒU",        "", "vender", "VER"],
    ["HUÒ",         "", "bienes", "NOM"],
    ["SHÌ",         "", "probarse, intentar", "VER"],
    ["JUÉDE",       "", "sentir, pensar", "VER"],
    ["HÉSHÌ",       "", "adecuado, apropiado, correcto", "ADJ"],
    ["DUǍN",        "", "corto", "ADJ"],
    ["CHÁNG",       "", "largo", "ADJ"],
    ["GĀO",         "", "elevado, alto", "ADJ"],
    ["GŌNGFĒN",     "", "centímetro", "NOM"],
    ["MÁFAN",       "", "molestar, preocupar (a alguien)", "VER"],
    ["SĪCHÓU",      "", "seda", "NOM"],
    ["XĪFÚ",        "", "ropa occidental / traje", "NOM"]
]
