#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON11 = [
    ["HUÌ",        "", "saber hacer algo (habilidad aprendida)", "VAUX"],
    ["YĪDIǍNR",    "", "un poco", "CLA"],
    ["SĪJĪ",       "", "conductor, chofer", "NOM"],
    ["DIǍNZHŌNG",  "", [["en punto", "CLA"], ["reloj", "NOM"]]],
    ["CHÀ",        "", "estar corto de, carecer de", "VER"],
    ["KÈ",         "", [["un cuarto (de hora)", "CLA"], ["trimestre", "NOM"]]],
    ["HUÍ",        "", "volver", "VER"],
    ["SHÀNGKÈ",    "", "ir a clase", "V+O"],
    ["JIĀO",       "", "enseñar", "VER"],
    ["NÉNG",       "", "poder hacer algo (habilidad física o posiblidad de hacerlo)", "VAUX"],
    ["DÀO",        "", "llegar, alcanzar", "VER"],
    ["NǍLI",       "", "no (expresión de negación que denota modestia)", "FH"],
    ["YĪNGYǓ",     "", "inglés (idioma)", "NOM"],
    ["SŪNNÜR",     "", "nieta por parte de hijo", "NOM"],
    ["NǙ'ÉR",      "", "hija", "NOM"],
    ["SUÌSHU",     "", "años (edad)", "NOM"],
    ["SHÙ",        "", "número", "NOM"],
    ["HÁI",        "", "además / todavía", "ADV"],
    ["FĒN",        "", "minuto", "CLA"],
    ["BÁIBÁI",     "", "adiós", "FH"],

    ["WÈISHÉNME",  "", "¿por qué?, ¿para qué?", "PI"],
    ["WÈI",        "", "para", "PRE"],
    ["ZUÓTIĀN",    "", "ayer", "NOM"],
    ["DŌNGXI",     "", "cosas, objetos", "NOM"],
    ["WÁNR",       "", "pasarlo bien, jugar", "VER"],
    ["WǍNSHANG",   "", "tarde, noche", "NOM"],
    ["BÀN",        "", "mitad, media", "CLA"],
    ["XIĚ",        "", "escribir", "VER"],
    ["HÀNZÌ",      "", "carácter chino", "NOM"],
    ["ZÌ",         "", "carácter, palabra", "NOM"],
    ["SHUÌJIÀO",   "", "dormir, ir a la cama", "V+O"],
    ["SHUÌ",       "", [["dormir", "VER"], ["sueño", "NOM"]]],
    ["QǏCHUÁNG",   "", "levantarse", "V+O"],
    ["QǏ",         "", "levantarse, ponerse en pie, elevar", "VER"],
    ["CHUÁNG",     "", "cama", "NOM"],
    ["YĪNGGĀI",    "", "debería", "VAUX"],
    ["GĀI",        "", "debería", "VAUX"],
    ["WÈNTÍ",      "", "pregunta, problema", "NOM"],
    ["KĚYǏ",       "", "puede que", "VAUX"]
]
