#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON18 = [
    ["JÌ",            "", "recordar", "VER"],
    ["CUÒ",           "", "incorrecto", "ADJ"],
    ["BĀOGUǑ",        "", "paquete, parcela", "NOM"],
    ["BĀO",           "", [["envolver", "VER"], ["bolsa", "NOM"]]],
    ["XIĒ",           "", "alguno(s)", "CLA"],
    ["YĪNGWÉN",       "", "inglés (idioma)", "NOM"],
    ["CÍDIǍN",        "", "diccionario", "NOM"],
    ["JIÙ",           "", "viejo, pasado, usado", "ADJ"],
    ["XĪN",           "", "nuevo", "ADJ"],
    ["WǍNG",          "", "hacia", "PRE"],
    ["HÁNGKŌNG",      "", "aviación", "NOM"],
    ["KŌNG",          "", "cielo, aire", "NOM"],
    ["HǍIYÙN",        "", "transporte marítimo", "NOM"],
    ["HǍI",           "", "océano, mar, gran lago", "NOM"],
    ["YÓUFÈI",        "", "franqueo, gastos de envío", "NOM"],
    ["FÈI",           "", "gasto, costo", "NOM"],
    ["QǓ",            "", "tomar, agarrar, recoger", "VER"],
    ["TŌNGZHĪDĀN",    "", "carta de aviso", "VER"],
    ["TŌNGZHĪ",       "", [["comunicar, notificar, informar", "VER"], ["notificación", "NOM"]]],
    ["DĀN",           "", "hoja de papel", "NOM"],
    ["HǍIGUĀN",       "", "aduana", "NOM"],
    ["BIÉ",           "", "no", "ADV"],
    ["HÙZHÀO",        "", "pasaporte", "NOM"],
    ["KÈQI",          "", "cortés, atengo", "ADJ"],
    ["JIÀNGUÓMÉN",    "", "lugar en Beijing", "NP"],
    ["MÉN",           "", "puerta, entrada", "NOM"],

    ["LÙ",            "", "línea (de autobús) / camino", "NOM"],
    ["GŌNGGÒNGQÌCHĒ", "", "autobús público", "NOM"],
    ["GŌNGGÒNG",      "", "público", "ADJ"],
    ["QÌCHĒ",         "", "automóvil", "NOM"],
    ["CHĒ",           "", "vehículo", "NOM"],
    ["JĪNGGUÒ",       "", "pasar, atravesar, pasar por", "VER"],
    ["HǍOXIÀNG",      "", "parecer", "VER"],
    ["XIÀNG",         "", "parecer", "VER"],
    ["ZÁNMEN",        "", "nosotros", "PRO"],
    ["SHÒUPIÀOYUÁN",  "", "vendedor de boletos / conductor", "NOM"],
    ["PIÀO",          "", "boleto, entrada", "NOM"],
    ["DÀJIĀ",         "", "todos, todo el mundo", "PRO"],
    ["LǏBIAN",        "", "adentro, interior", "NOM"],
    ["BIAN",          "", "lado", "NOM"],
    ["ZHÀN",          "", "estación, parada", "NOM"],
    ["CHÉNGKÈ",       "", "pasajero", "NOM"],
    ["CHÉNG",         "", "viajar, tomar", "VER"],
    ["KÈ",            "", "visitante, invitado", "NOM"],
    ["DÌTIĚ",         "", "metro", "NOM"],
    ["FÀNGXĪN",       "", "tranquilizarse, relajarse", "VMO"],
    ["ZĀOGĀO",        "", "desastre, muy malo", "ADJ"],
    ["QIÁNMÉN",       "", "lugar en Beijing ", "NP"]
]
