#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON15 = [
    ["ZǍO",            "", [["temprano", "ADJ"], ["mañana", "NOM"]]],
    ["YÍNHÁNG",        "", "banco", "NOM"],
    ["SHǍO",           "", "poco", "ADJ"],
    ["PÁIDUÌ",         "", "hacer cola", "V+O"],
    ["PÁI",            "", [["ordenar", "VER"], ["fila", "NOM"]]],
    ["DUÌ",            "", "fila de personas", "NOM"],
    ["HUÀN",           "", [["cambiar", "VER"], ["cambio", "NOM"]]],
    ["YĪNGBÀNG",       "", "libras esterlinas", "NOM"],
    ["RÉNMÍNBÌ",       "", "RMB", "NOM"],
    ["RÉNMÍN",         "", "pueblo", "NOM"],
    ["DĚI",            "", "tener que, deber de, necesidad", "VAUX"],
    ["YÒNG",           "", "utilizar", "VER"],
    ["GĀNG",           "", "recién", "ADV"],
    ["CÓNG",           "", "desde", "PRE"],
    ["DÀO",            "", "hasta", "PRE"],
    ["FĒICHÁNG",       "", "extremadamente", "ADV"],
    ["CÌ",             "", "clasificador de acciones", "CLA"],
    ["CĀNGUĀN",        "", "visitar", "VER"],
    ["BĪNGMǍOYǑNG",    "", "guerreros de terracota", "NOM"],
    ["BĪNG",           "", "soldado, luchador", "NOM"],
    ["MÍNGXÌNPIÀN",    "", "postal", "NOM"],
    ["XÌN",            "", "carta", "NOM"],
    ["GĀI",            "", "tocarle hacer una cosa", "VER"],
    ["GŌNGZUÒRÉNYUÁN", "", "empleado", "NOM"],
    ["RÉNYUÁN",        "", "personal", "NOM"],
    ["QIĀN",           "", "mil", "NUM"],
    ["SHǓ",            "", "contar", "VER"],
    ["WÁNGFǓJǏNG",     "", "zona comercial de Beijing", "NP"],
    ["XĪĀN",           "", "capital de la provincia de Shaanxi", "NP"],

    ["HǍOJIǓBÚJIÀN",   "", "¡cuánto tiempo sin verte!", "FH"],
    ["HǍOJIǓ",         "", "hace mucho tiempo", "ADV"],
    ["JIÀN",           "", "ver", "VER"],
    ["FĀZHǍN",         "", "desarrollar", "VER"],
    ["KUÀI",           "", "rápido", "ADJ"],
    ["HUÀ",            "", "dialecto, idioma", "NOM"],
    ["PǓTŌNGHUÀ",      "", "lengua común (mandarín)", "NOM"],
    ["NIÁNQĪNG",       "", "joven", "ADJ"],
    ["QĪNG",           "", "ligero, pequeño", "ADJ"],
    ["LIÚLÌ",          "", "fluido", "ADJ"],
    ["DǑNG",           "", "entender", "VER"],
    ["JIÙ",            "", "con exactitud, exactamente / ahora mismo", "ADV"]
]
