#!/usr/bin/env python
# -*- coding: utf-8 -*-

LESSON19 = [
    ["ZHŌNGGUÓHUÀ",   "", "pintura tradicional china", "NOM"],
    ["HUÀ",           "", "pintar", "VER"],
    ["HUÀR",          "", "cuadro, pintura", "NOM"],
    ["YÓUHUÀ",        "", "pintura al óleo", "NOM"],
    ["YÓU",           "", "aceite", "NOM"],
    ["YÍYÀNG",        "", "mismo", "ADJ"],
    ["MĚISHÙGUǍN",    "", "galería de arte", "NOM"],
    ["KĀIMÉN",        "", "abrir la puerta / abrir negocio", "VMO"],
    ["GUĀNMÉN",       "", "cerrar la puerta / cerrar negocio", "VMO"],
    ["LǍO",           "", "viejo, con experiencia", "ADJ"],
    ["HUÀJIĀ",        "", "pintor, artista", "NOM"],
    ["JIĀ",           "", "especialista", "NOM"],
    ["BÙGǍNDĀNG",     "", "(respuesta de modestia ante un cumplido)", "FH"],
    ["ÀIHÀO",         "", [["gustar, tener algo como hobby", "VER"], ["hobby", "NOM"]]],
    ["CHÀNGGĒ",       "", "cantar (una canción)", "VER"],
    ["CHÀNG",         "", "cantar", "VER"],
    ["MǍMǍHŪHŪ",      "", "más o menos", "ADJ"],
    ["MǍHU",          "", "descuidado, casual", "ADJ"],
    ["HǓ",            "", "tigre", "NOM"],
    ["FÚ",            "", "clasificador de cuadros, pinturas, etc.", "CLA"],
    ["XÚ BĒIHÓNG",    "", "nombre de un famoso pintor chino", "NP"],

    ["DIÀNTĪ",        "", "ascensor", "NOM"],
    ["KĀI WÁNXIÀO",   "", "hacer una broma", "VMO"],
    ["CÁILIÀO",       "", "material", "NOM"],
    ["ZHǏ",           "", "papel", "NOM"],
    ["BÙ",            "", "tela", "NOM"],
    ["ZHǓYÀO",        "", "principal", "ADJ"],
    ["MÒ",            "", "tinta china", "NOM"],
    ["YÓUCǍI",        "", "maquillaje teatral", "NOM"],
    ["BIÉDE",         "", "otro", "PRO"],
    ["KÒNGBÁI",       "", "espacio en blanco ", "NOM"],
    ["ZHǏ",           "", "solamente", "ADV"],
    ["PǏ",            "", "clasificador para caballos", "CLA"],
    ["XIǍNGXIÀNG",    "", [["imaginar", "VER"], ["imaginación", "NOM"]]],
    ["PǍO",           "", "correr", "VER"],
    ["TĀ",            "", "él (para animales) / eso (para cosas)", "PRO"],
    ["FĒNG",          "", "viento", "NOM"],
    ["XIĀ",           "", "camarón", "NOM"],
    ["YÓU",           "", "nadar", "VER"],
    ["QÍ BÁISHÍ",     "", "nombre de un pintor chino", "NP"]
]
